### ISSUE TITLE
Support to enable/disabe HTML messages 

### ISSUE THREAD

**Issue by karthick-manoharan** [emonney/ngx-toasta#11]
**Feature request:**
At present any HTML or JavaScript codes passed as message becomes executed in the notification message.

**Reasons for request:**
1. This will lead to message getting executed which leads to vulnerability.
2. Good to have feature.

**Steps to reproduce:**
1. Use `<h1>Test</h1>` as message. And notice the notification message displayed

**Comment by emonney** [comment]
Javascript code is not executed. HTML if present is sanitized and rendered to give users the option to show rich content in toasts
