### ISSUE TITLE
Styling not being applied - followed documentation

### ISSUE THREAD

**Issue by AlexCharlton93** [emonney/ngx-toasta#5]
Hi,

I'm having difficulty getting the styling to work,

I've downloaded the example project, and seen that imports 'toasta-styles.css', So I've tried copying this file into my project and importing it, but I still only recieve the toast text on screen when clicking the button.

Any idea where I am going wrong..?

TIA,
Alex

**Comment by StefanKennedy** [comment]
It might be related to an issue with ng-bootstrap: https://github.com/ng-bootstrap/ng-bootstrap/issues/2945

**Comment by StefanKennedy** [comment]
Adding this line to styles.css fixed it for me:

`@import 'ngx-toasta/styles/style-material.css';`

:+1:
