### ISSUE TITLE
Angular 15 support ( please change package.json peerDependencies)

### ISSUE THREAD

**Issue by MarisaNat** [emonney/ngx-toasta#51]
Hi,

I can not properly use the template which I bought from you and updated to Angular 15 because your ngx-toasta package.json restricts the angular peerDependencies to be <15.0.0

  "peerDependencies": {
    "@angular/common": ">=6.0.0 <15.0.0",
    "@angular/core": ">=6.0.0 <15.0.0",
    "rxjs": ">=6.0.0"
  },

Could you please remove this upper restriction? As far as I tested it ngx-toasta works perfectly fine with Angular 15

Thanks a lot!

**Comment by emonney** [comment]
Hello Marisa,

I'll work on this before end of week.
In the mean time you can use `npm install --legacy-peer-deps` to bypass the restriction.

**Comment by StefanoZambolin** [comment]
Hi, are there news about Angular 15.0.0 compatibility?
Thanks

**Comment by emonney** [comment]
Version 4.0.0 (compatible with ng15) has been released

**Comment by MarisaNat** [comment]
Hi,
thanks a lot for fixing this 😊
Have a nice week!

Marisa

Von: Ebenezer Monney ***@***.***>
Gesendet: Donnerstag, 23. Februar 2023 01:14
An: emonney/ngx-toasta ***@***.***>
Cc: Marisa Kraft ***@***.***>; Author ***@***.***>
Betreff: Re: [emonney/ngx-toasta] Angular 15 support ( please change package.json peerDependencies) (Issue #51)


Hello Marisa,

I'll work on this before end of week.
In the mean time you can use npm install --legacy-peer-deps to bypass the restriction.
