### ISSUE TITLE
Angular 8 support

### ISSUE THREAD

**Issue by symonfly82** [emonney/ngx-toasta#6]
Is it possible to update the dependencies for using Angular 8?

when running ng update @angular/cli @angular/core it show up:
Package "ngx-toasta" has an incompatible peer dependency to "@angular/common" (requires "^6.0.0-rc.0 || ^6.0.0" (extended), would install "8.0.0").
                  Package "ngx-toasta" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0-rc.0 || ^6.0.0" (extended), would install "8.0.0").

Thanks a lot

**Comment by emonney** [comment]
This has been added in version [1.0.2](https://www.npmjs.com/package/ngx-toasta/v/1.0.2)
