### ISSUE TITLE
Position Ignored

### ISSUE THREAD

**Issue by eappell** [emonney/ngx-toasta#7]
I'm using this in a couple apps, and recently tried moving the position from the default to top-center, and top-fullwidth, but the code ignores those settings.  I've instantiated the ToastaConfig in my constructor, as is described in the docs.  I set the theme to material, and the position to "top-center".  The toast DOES use the material theme, but it's in the lower-right corner, no matter what I do.

Here's my (abbreviated) code: 
` 
constructor (
        private toastaService: ToastaService,
        private toastaConfig: ToastaConfig
    ) {
      this.toastaConfig.theme = 'material';
      this.toastaConfig.position = 'top-fullwidth';
     }

    someFunction() {
          const message = "This is the message";
          const toastOptions: ToastOptions = {
            title: 'The Title',
            msg: message,
            showClose: true,
            timeout: 15000
          };
          this.toastaService.warning(toastOptions);
    }
`
Sorry, editor's not liking my code formatting for some reason...  Anyways, you get the idea.  Theme, good, position, no good.  Any ideas?

Thanks for the help!

**Comment by MojtabaMontazery** [comment]
I also got that issue recently when `position` from `toastConfig` is not respected. The workaround for that might be to set the position on `ngx-toasta` component directly like `<ngx-toasta [position]="'top-right'"></ngx-toasta>`.

**Comment by emonney** [comment]
Fixed in earlier versions
