### ISSUE TITLE
Error: 404 Not Found - GET https://registry.npmjs.org/ngx-tosta - Not found

### ISSUE THREAD

**Issue by DebolaA** [emonney/ngx-toasta#8]
**i get the below error when i run npm install ngx-toasta**

some please help to resolve, thank you

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'ngx-tosta' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose npm-session 9af96d34f07e308c
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/ngx-tosta 682ms
8 http fetch GET 404 https://registry.npmjs.org/ngx-tosta 614ms
9 silly fetchPackageMetaData error for ngx-tosta@latest 404 Not Found - GET https://registry.npmjs.org/ngx-tosta - Not found
10 timing stage:rollbackFailedOptional Completed in 1ms
11 timing stage:runTopLevelLifecycles Completed in 2441ms
12 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/ngx-tosta - Not found
12 verbose stack     at res.buffer.catch.then.body (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:104:15)
12 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
13 verbose statusCode 404
14 verbose pkgid ngx-tosta@latest
15 verbose cwd C:\Acomos\acomosonline
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ngx-tosta"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code E404
21 error 404 Not Found - GET https://registry.npmjs.org/ngx-tosta - Not found
22 error 404
23 error 404 'ngx-tosta@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]

**Comment by emonney** [comment]
You're typing it wrong. Its ngx-toasta not ngx-tosta. Check your spellings

**Comment by DebolaA** [comment]
yes that was it thank you for the prompt reply.
